[pytest]
pythonpath = src
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests

# Coverage
addopts = 
    --verbose
    --strict-markers
    --tb=short
    --disable-warnings

# Ignore paths
norecursedirs = 
    .git
    .github
    __pycache__
    notebooks
    resources